src/kelnero/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

from django.contrib import admin
admin.autodiscover()


def _url(name, pat):
    return url(r'^%s$' % pat, name, name=name)


def client(name, pat):
    return url(r'^client/(?P<client_key>[a-z0-9]+)/%s$' % pat, name, name=name)


urlpatterns = patterns('kelnero.views',
    # Anonymous user urls.
    _url('home',             r''),
    _url('new_client',       r'bill/(?P<bill_code>\d{6})/new-client/'),

    # Client urls.
    client('items',          r'items/'),
    client('items',          r'items/(?P<parent>\d+)/'),
    client('client_orders',  r'orders/'),
    client('add_friend',     r'friends/add/'),
    client('friends',        r'friends/'),
    client('client_details', r'details/'),

    # Waiter urls.
    _url('waiter',           r'waiter/'),
    _url('bill_orders',      r'bills/(?P<bill_id>\d+)/orders/'),
    _url('order_details',    r'bills/(?P<bill_id>\d+)/orders/(?P<order_id>\d+)/'),

    _url('bills',            r'bills/'),
    _url('bill',             r'bills/(?P<bill_id>\d+)/'),
    _url('client_bill',      r'bills/(?P<bill_id>\d+)/clients/(?P<client_id>\d+)/'),

    url(r'^bills-paid/$', 'bills', {'show_paid': True}, name='paid_bills'),
    url(r'^bills-paid/(?P<bill_id>\d+)/$', 'bill', {'show_paid': True}, name='paid_bill'),
    url(r'^bills-paid/(?P<bill_id>\d+)/clients/(?P<client_id>\d+)/$', 'client_bill',
        {'show_paid': True}, name='paid_client_bill'),

    url(r'^admin/menu/', include('kelnero.manager.menu.urls')),
    url(r'^admin/codes/', include('kelnero.manager.codes.urls')),
    #url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', dict(
        next_page=reverse_lazy('waiter'),
    ), name='logout'),
)

src/kelnero/models.py
# coding: utf-8
from __future__ import unicode_literals

import string

from django.db import models
from django.utils.translation import ugettext_lazy as _

from mptt.models import MPTTModel
from mptt.models import TreeForeignKey

from kelnero.utils.gencode import gen_code


class Item(MPTTModel):
    name = models.CharField(_('Pavadinimas'), max_length=128)
    treename = models.CharField(
        _('Pavadinimas sąraše'), max_length=128, default='', blank=True,
        help_text=_(
            'Pavadinimas sąraše turi būti sutrumpintas pavadinimo variantas. '
            'Jei nenurodyta, bus naudojamas paprastas pavadinimas.'
        ),
    )
    parent = TreeForeignKey(
        'self', null=True, blank=True, related_name='children'
    )
    price = models.DecimalField(
        _('Kaina'),
        max_digits=5, decimal_places=2, null=True, blank=True
    )
    ended = models.BooleanField(_('Baigėsi'), default=False, help_text=_(
        'Jei pažymėta, reiškia, kad produktas baigėsi. Pasibaigę produktai '
        'nerodomi meniu. Visiems užsisakiusiems pranešama, kad šis '
        'produktas baigėsi ir nebus pateiktas.'
    ))

    class MPTTMeta:
        order_insertion_by = ['name']

    def __unicode__(self):
        return self.name

    def get_indent(self):
        return '%dpx' % (((self.level + 1) * 10) + 10)

    def get_tree_name(self):
        return self.treename or self.name

    def is_category(self):
        return self.price is None


class Table(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __unicode__(self):
        return self.name


class Bill(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    table = models.ForeignKey(Table)
    code = models.CharField(max_length=16, blank=True, unique=True)

    def set_random_code(self):
        code = gen_code()
        while Bill.objects.filter(code=code).exists():
            code = gen_code()
        self.code = code

    def save(self, *args, **kwargs):
        if self.code == '':
            self.set_random_code()
        super(Bill, self).save(*args, **kwargs)


class Waiter(models.Model):
    name = models.CharField(max_length=128)

    def __unicode__(self):
        return self.name


class Client(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    bill = models.ForeignKey(Bill)
    name = models.CharField(max_length=128)
    code = models.CharField(max_length=16, blank=True)
    key = models.CharField(max_length=12, blank=True, unique=True, editable=False)
    friend = models.ForeignKey('self', null=True, blank=True)

    class Meta:
        unique_together = (
            ('bill', 'name'),
            ('bill', 'code'),
        )

    def __unicode__(self):
        return self.name

    def set_random_code(self):
        self.code = gen_code()

    def set_random_key(self):
        size = 12
        alphabet = string.digits + string.ascii_lowercase
        key = gen_code(size, alphabet)
        while Client.objects.filter(key=key).exists():
            key = gen_code(size, alphabet)
        self.key = key

    def save(self, *args, **kwargs):
        if self.code == '':
            self.set_random_code()
        if self.key == '':
            self.set_random_key()
        super(Client, self).save(*args, **kwargs)


class Order(models.Model):
    CREATED   = 0
    CONFIRMED = 1
    ACCEPTED  = 2
    DELIVERED = 3
    PAID      = 4
    CANCELED  = 5
    STATUS_CHOICES = (
        (CREATED,   _('Nepatvirtintas')),
        (CONFIRMED, _('Užsakyta')),
        (ACCEPTED,  _('Priimta')),
        (DELIVERED, _('Atnešta')),
        (PAID,      _('Sumokėta')),
        (CANCELED,  _('Atšauktas')),
    )

    created = models.DateTimeField(auto_now_add=True)
    client = models.ForeignKey(Client)
    item = models.ForeignKey(Item)
    note = models.TextField(default='', blank=True)
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES, default=CREATED
    )
    cancel_reason = models.TextField(blank=True)


class OrderStatus(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    waiter = models.ForeignKey(Waiter, null=True)
    order = models.ForeignKey(Order)
    status = models.PositiveSmallIntegerField(choices=Order.STATUS_CHOICES)
    cancel_reason = models.TextField(blank=True)

src/kelnero/templates/partials/bills_menu.html
{% load i18n %}
<ul class="nav nav-pills">
  {% if show_paid %}
  <li><a href="{% url "bills" %}">{% trans "Neapmokėtos" %}</a></li>
  <li class="active"><a href="#">{% trans "Apmokėtos" %}</a></li>
  {% else %}
  <li class="active"><a href="#">{% trans "Neapmokėtos" %}</a></li>
  <li><a href="{% url "paid_bills" %}">{% trans "Apmokėtos" %}</a></li>
  {% endif %}
</ul>

src/kelnero/templates/partials/client_orders_table.html
{% load i18n %}
{% if orders %}
<table class="table">
  <thead>
  <tr>
    <th>{% trans "Pavadinimas" %}</th>
    <th>{% trans "Kaina" %}</th>
  </tr>
  </thead>
  <tbody>
  {% for order in orders %}
  <tr>
    <td>
      {% if order.status == Order.CANCELED %}
      <del>{{ order.item }}</del>
      {% if order.cancel_reason %}
      <p class="text-danger">{{ order.cancel_reason }}</p>
      {% endif %}
      {% else %}
      {{ order.item }}
      {% endif %}
    </td>
    <td class="number">
      {% if order.status == Order.CANCELED %}
      <div><del>{{ order.item.price }}&nbsp;Lt.</del></div>
      {% else %}
      <div>{{ order.item.price }}&nbsp;Lt.</div>
      {% endif %}
      <div>
      {% include "partials/order_status_label.html" %}
      </div>
      {% if order.status == Order.CREATED %}
      <div class="order-buttons"><button type="submit" class="btn btn-default" name="delete" value="{{ order.pk }}">{% trans "Atšaukti" %}</button></div>
      {% endif %}
    </td>
  </tr>
  {% endfor %}
  </tbody>
  <tfoot>
  <tr class="bg-info">
    <th>
      {% if show_paid %}
      {% trans "Sumokėta" %}
      {% else %}
      {% trans "Mokėti" %}
      {% endif %}
    </th>
    <th class="number">{{ total }}&nbsp;Lt.</th>
  </tr>
  </tfoot>
</table>
{% else %}
<div class="well">{% trans "Užsakymų nėra." %}</div>
{% endif %}

src/kelnero/templates/partials/order_status_label.html
{% load i18n %}

{% if order.status == Order.CANCELED %}
<span class="label label-danger">{{ order.get_status_display }}</span>
{% elif order.status == Order.PAID %}
<span class="label label-info">{{ order.get_status_display }}</span>
{% elif order.status > Order.ACCEPTED %}
<span class="label label-success">{{ order.get_status_display }}</span>
{% else %}
<span class="label label-default">{{ order.get_status_display }}</span>
{% endif %}

src/kelnero/templates/partials/waiter_order_status.html
{% load i18n %}

{% if order.status == Order.CONFIRMED %}
<button class="btn btn-default" type="submit" name="order" value="{{ order.pk }}">{% trans "Priimti" %}</button>
{% elif order.status == Order.ACCEPTED %}
<button class="btn btn-default" type="submit" name="order" value="{{ order.pk }}">{% trans "Atnešta" %}</button>
{% else %}
{% include "partials/order_status_label.html" %}
{% endif %}